CExplorer.MVC/Entities/User.cs
using System;

namespace CExplorer.MVC.Entities
{
    public class User
    {
        public int Id { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

        public bool IsAdmin { get; set; }
    }
}

CExplorer.MVC/Models/ErrorViewModel.cs
using System;

namespace CExplorer.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CExplorer.MVC/Models/LoginVm.cs
using System.ComponentModel.DataAnnotations;

namespace CExplorer.MVC.Models
{
    public class LoginVm
    {
        [Required]
        [Display(Name = "E-mail")]
        public string EmailAdress { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

CExplorer.MVC/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CExplorer.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult NewCocktail()
        {
            return View();
        }
    }
}

CExplorer.MVC/Controllers/Home/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CExplorer.MVC.Models;

namespace CExplorer.MVC.Controllers.Home
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CExplorer.MVC/Controllers/Login/LoginController.cs
using CExplorer.MVC.Data;
using CExplorer.MVC.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Security.Claims;

namespace CExplorer.MVC.Controllers.Login
{
    public class LoginController : Controller
    {
        private readonly CExplorerContext _Context;

        public LoginController (CExplorerContext context)
        {
            _Context = context;
        }

        public IActionResult Index()
        {
            var login = new LoginVm();
            return View(login);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(LoginVm loginVm)
        {
            var user = _Context.Users.SingleOrDefault(g => g.Email == loginVm.EmailAdress);

            if(user != null)
                if(ModelState.IsValid)
                    if(string.Equals(user.Email, loginVm.EmailAdress, StringComparison.CurrentCultureIgnoreCase)
                        && loginVm.Password == user.Password)
                    {
                        ClaimsIdentity userIdentity;

                        if (user.IsAdmin)
                        {
                            userIdentity = new ClaimsIdentity(new[]
                                {
                                    new Claim(ClaimTypes.Email, user.Email),
                                    new Claim(ClaimTypes.Role, "Admin"),
                                },
                                "ApplicationCookie", ClaimTypes.Email, ClaimTypes.Role);
                        }
                        else
                        {
                            //Gewoone gebruikers
                            userIdentity = new ClaimsIdentity(new[]
                                {
                                    new Claim(ClaimTypes.Email, user.Email),
                                    new Claim(ClaimTypes.Role, "User"),
                                },
                                "ApplicationCookie", ClaimTypes.Email, ClaimTypes.Role);
                         }

                        ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                        HttpContext.SignInAsync(principal);

                        if (principal.IsInRole("Admin"))
                        {
                            return new RedirectToActionResult("Index", "Admin", null);
                        }
                    }

            ModelState.AddModelError(string.Empty, "The given login information was not correct.");
            return View(loginVm);
        }
    }
}

CExplorer.MVC/Controllers/Quiz/QuizController.cs
using Microsoft.AspNetCore.Mvc;

namespace CExplorer.MVC.Controllers.Quiz
{
    public class QuizController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult QuizStart()
        {
            return View();
        }
    }
}

CExplorer.MVC/Controllers/Recipes/RecipesController.cs
using System.Collections.Generic;
using CExplorer.MVC.Helpers;
using CExplorerService.lib.DTO;
using Microsoft.AspNetCore.Mvc;

namespace CExplorer.MVC.Controllers.Recipes
{
    public class RecipesController : Controller
    {
        readonly string baseuri = "https://localhost:44385/api/Cocktails";
        public IActionResult Index()
        {
            string uri = $"{baseuri}/basic";
            return View(WebApiHelper.GetApiResult<List<CocktailBasic>>(uri));
        }
    }
}

CExplorer.MVC/Areas/Admin/Views/Home/Index.cshtml
<div id="app">
   <article class="col-md-3">
       <h3>{{message}}</h3>
       <nav>
           <ul class="list-group">
               <li v-for="cocktail in cocktails" v-on:click="fetchCocktailDetails(cocktail)" style="cursor:pointer">
                   <span class="bookTitle">{{ cocktail.id }}</span>
                   <span class="bookTitle">{{ cocktail.name }}</span>
               </li>
           </ul>
       </nav>
   </article>

    <div v-if="currentCocktail" class="col-md-6">
        <h3>Details</h3>
        <div class="col-md-12">
            <div class="form-group">
                <label class="col-sm-2 control-label">Name</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" v-model="currentCocktail.name"/>
                </div>

                <label class="col-sm-2 control-label">Origin</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" v-model="currentCocktail.origin.country"/>
                </div>
            </div>
        </div>
        <h3>Ingredients</h3>
        <div class="form-group">
            <div class="col-md-12">
                <label class="col-sm-4">name</label>
                <label class="col-sm-4">volume</label>
                <label class="col-sm-4">dosage</label>
            </div>
            <div class="col-md-12">
                <div v-for="ingredient in currentCocktail.ingredients">
                    <input v-model="ingredient.name" />
                    <input v-model="ingredient.volume" />
                    <input v-model="ingredient.dosage"/>
                </div>
                <div>
                    <button class="btn btn-primary" v-on:click="UpdateCocktail">Save Changes</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/js/vue.js"></script>
    <script src="~/js/Admin.js"></script>
}

CExplorer.MVC/Areas/Admin/Views/Home/NewCocktail.cshtml
<h2>New Cocktail</h2>
<div id="app">
    <div class="col-md-4 form-horizontal">
        <h3>Details</h3>
        <div class="form-group">
            <label class="col-sm-2 control-label small">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" v-model="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label small">Origin</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" v-model="">
            </div>
        </div>
    </div>

    @*<div class="col-md-4 form-horizontal">
        <h3>Ingredients</h3>
        <div class="form-group">
            <label class="col-sm-12 control-label small">From Existing ingredients</label>
            <select class="form-control">
                <option v-for="ingredient in ingredients" :value="ingredient">{{ingredient.name}}</option>
            </select>
        </div>
    </div>*@
</div>
@section scripts{
    <script src="~/js/vue.js"></script>
    <script src="~/js/Admin.js"></script>
}

CExplorer.MVC/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Cocktail Explorer</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <!--NavBar-->
    <nav class=" navbar-inverse CENavBar col-md-12">
        <div class="container">
            <div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Recipes" asp-action="Index">Recipes</a></li>
                    <li><a asp-area="" asp-controller="Quiz" asp-action="Index">Quiz</a></li>
                    <li><a asp-area="Admin" asp-controller="Home" asp-action="Index">Cocktail List</a></li>
                    <li><a asp-area="Admin" asp-controller="Home" asp-action="NewCocktail">New Cocktail</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!--NavBar End-->

    <partial name="_CookieConsentPartial" />

    <div class="container">
        <div style="margin-top:150px;">
            @RenderBody()
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CExplorer.MVC/Views/Home/Index.cshtml
<h2>HOME</h2>

<main class="col-md-12 text-center modal-content" style="padding:10px; margin:10px;">
    <div>
        <h3 class="text-center">Welcome to the Cocktail Explorer</h3>
        <p>On this site you can learn all about cocktails through a serie of quiz questions.</p>
        <p>Or though our cocktail recipe list</p>
    </div>
</main>

CExplorer.MVC/Views/Login/Index.cshtml
@model CExplorer.MVC.Models.LoginVm

<div>
    <h1 style="text-align:center;">Login</h1>

    <div asp-validation-summary="ModelOnly"></div>
    <form asp-action="Login" class="form-horizontal">
        <div class="form-group form-inline text-center">
            <label asp-for="EmailAdress" class="control-label"></label>
            <div class="col-sm-12">
                <input asp-for="EmailAdress" class="form-control" />
                <span asp-validation-for="EmailAdress"></span>
            </div>
        </div>
        <div class="form-group form-inline text-center">
            <label asp-for="Password" class="control-label"></label>
            <div class="col-sm-12">
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password"></span>
            </div>
        </div>
        <div class="form-group form-inline text-center">
            <div class="col-sm-12">
                <button type="submit" class="btn btn-lg">Login</button>
            </div>
        </div>
    </form>
</div>

CExplorer.MVC/Views/Quiz/Index.cshtml
<h2>Quiz</h2>

<div class="col-md-12" style="margin:10px;">
    <a asp-controller="Quiz" asp-action="QuizStart"><span style="font-size:large;">Start Quiz</span></a>
</div>

CExplorer.MVC/Views/Quiz/QuizStart.cshtml
<div style="margin:5px;">
    <h3 class="col-md-12">Cocktail Explorer Quiz</h3>

    <div id="question" class="col-md-8"></div>

    <div class="col-md-2" id="score"></div>

    <div id="cocktail" class="col-md-12" style="display:table-row-group; border-bottom:solid 1px white; margin-bottom:5px;"></div>

    <div class="col-md-4">
        <ul id="ingredients" class="list-group IngredientList"></ul>
    </div>

    <div class="col-sm-3">
        <div id="answer1" class="answers"></div>
        <div id="answer2" class="answers"></div>
        <div id="answer3" class="answers"></div>
        <div id="answer4" class="answers"></div>
    </div>
</div>

@section scripts
    {
    <script>
        var url = 'https://localhost:44385/api/Questions/random';
        var correctanswer = 'none';
        var score = 0;

        $(document).ready(function () {
            $.getJSON(url)
                .done(function (data) {
                    GetQuestionData(data)
                });
        });

        $(document).ready(function () {
            $(".answers").on('click', function (data) {
                if (data.currentTarget.innerText == correctanswer)
                    score = score + 1;
                $.getJSON(url)
                    .done(function (data) {
                        ClearAll()
                        GetQuestionData(data)
                    });
            });
        });

        function GetQuestionData(data) {
            if (data.partial == "GuessCocktail") {
                GetGuessCocktailData();
            }
            else if (data.partial == "GuessIngredient") {
                GetGuessIngredientData();
            }
            else if (data.partial == "GuessOrigin") {
                GetGuessOriginData();
            }
            $('<p>', { text:'Score : '+ score.toString() }).appendTo($('#score'));
            $('<h4>', { text: data.question }).appendTo($('#question'));
        }

        var irl = 'https://localhost:44385/api/Questions';

        function GetGuessCocktailData() {
            fetch(irl + '/guesscocktail')
                .then(responds => responds.json())
                .then(function (data) {
                    correctanswer = data.cocktail.name;
                    SetIngredients(data)
                    SetAnswers(data)
                })
        };

        function GetGuessIngredientData() {
            fetch(irl + '/guessingredient')
                .then(responds => responds.json())
                .then(function (data) {
                    correctanswer = data.correctanswer;
                    SetCocktail(data)
                    SetIngredients(data)
                    SetAnswers(data)
                })
        };
        
        function GetGuessOriginData() {
            fetch(irl + '/guessorigin')
                .then(responds => responds.json())
                .then(function (data) {
                    correctanswer = data.cocktail.origin;
                    SetCocktail(data)
                    SetAnswers(data)
                })
        }

        function SetCocktail(data) {
            $('<h4>', { text:'Cocktail : '+ data.cocktail.name }).appendTo($('#cocktail'));
        }

        function SetIngredients(data) {
            $.each(data.cocktail.ingredients, function (key, item) {
                debugger;
                $('<li>', { text: formatItem(item) })
                    .appendTo($('#ingredients'));
            })
        }

        function SetAnswers(data) {
            debugger;
            $('<button>', { text: data.answer1 })
                .appendTo($('#answer1'));

            $('<button>', { text: data.answer2 })
                .appendTo($('#answer2'));

            $('<button>', { text: data.answer3 })
                .appendTo($('#answer3'));

            $('<button>', { text: data.answer4 })
                .appendTo($('#answer4'));
        }

        function ClearAll() {
            $('#question').empty();
            $('#ingredients').empty();
            $('#cocktail').empty();
            $('#answers').empty();
            $('#answer1').empty();
            $('#answer2').empty();
            $('#answer3').empty();
            $('#answer4').empty();
            $('#score').empty();
        }

        function formatItem(item) {
            return item.name + ' ' + item.volume + ' ' + item.dosage;
        }
    </script>
}

CExplorer.MVC/Views/Recipes/Index.cshtml
@using CExplorerService.lib.DTO
@model List<CocktailBasic>


<div class="col-md-12">
    <div class="col-md-4">
        <h2>Recipes</h2>
        <ul class="list-group">
            @foreach (CocktailBasic cocktail in Model)
            {
                <li class="Cocktail">
                    <b><a href="#" data-id="@cocktail.Id" class="Cocktail">@cocktail.Name</a></b>
                </li>
            }
        </ul>
    </div>

    <div class="col-md-4">
        <h2>Ingredients</h2>
        <ul id="ingredients" class="list-group IngredientList"></ul>
    </div>
</div>

@section scripts
    {
    <script>
        $(document).ready(function () {

            var url = 'https://localhost:44385/api/Ingredients/basic';

            $(".Cocktail").on('click', function () {
                $.getJSON(url + '/' + $(this).data('id'))
                    .done(function (data) {
                        $.each(data, function (key, item) {
                            $('<li>', { text: formatItem(item) })
                                .appendTo($('#ingredients'));
                        })
                    });
                $('#ingredients').empty();
            });
        });

        function formatItem(item) {
            return item.name + ' ' + item.volume + ' ' + item.dosage;
        }
    </script>
}  

CExplorer.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cocktail Explorer</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <!--Carousel start-->
    <div id="myCarousel" class="carousel CECarousel" data-ride="carousel" data-interval="10000">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="/images/Carousel1.png" alt="" class="img-responsive">
                <div class="carousel-caption" role="option"></div>
            </div>
            <div class="item">
                <img src="/images/Carousel2.png" alt="" class="img-responsive">
                <div class="carousel-caption" role="option"></div>
            </div>
            <div class="item">
                <img src="/images/Carousel3.png" alt="" class="img-responsive">
                <div class="carousel-caption" role="option"></div>
            </div>
        </div>

        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <!--Carousel End-->
    <!--NavBar-->
    <nav class="navbar navbar-inverse CENavBar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Recipes" asp-action="Index">Recipes</a></li>
                    <li><a asp-area="" asp-controller="Quiz" asp-action="Index">Quiz</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!--NavBar End-->

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="navbar-fixed-bottom Footer">
            <div class="container">
                <div class="row text-center">
                    <div class="col-md-12">
                        <p>By using this site, you agree to the Terms of Use and Privacy Policy. CocktailExplorer® is a registered trademark of the Wayne Foundation, Inc., a non-profit organization.</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>